# Fonts
font_family        Atkinson Hyperlegible Mono
font_size 16.0
disable_ligatures always

# Cursor
cursor_stop_blinking_after 0

# Mouse
detect_urls no

# Tab bar
tab_bar_edge top
tab_bar_style separator
tab_separator "┇"
tab_title_template "     {title}     "
active_tab_font_style bold

# Color scheme
include tokyonight.conf

# macOS
macos_titlebar_color #2D303E

# Keyboard shortcuts
map cmd+enter new_window_with_cwd
map cmd+w close_window
map cmd+t new_tab_with_cwd
